### ISSUE TITLE
Continual loading

### ISSUE THREAD

**Issue by lowaire-digital** [zenika-open-source/FAQ#256]
**Issue**
Continually loading after full install and configuration.

**Error Message**
Preparing the questions...

**Error Output**
UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property title of 'undefined' or 'null'.
at err (/root/zenika/FAQ/server/src/endpoints/configuration.js:20:39)
at getConfiguration (/root/zenika/FAQ/server/src/middlewares/configuration.js:10:3)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
(node:22941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by MailyLehoux** [comment]
Hi, I really would like to contribute to this project, but I have the same issue. Someone know why ? Thanks
